<?php
/**
 * @file
 * Implements a Q&A platform for CI&T collaborators.
 */

module_load_include('inc', 'contribute', 'contribute.question');
module_load_include('inc', 'contribute', 'contribute.answer');
module_load_include('inc', 'contribute', 'contribute.comment');
module_load_include('inc', 'contribute', 'gamification');

/**
 * Define menu items and page callbacks.
 *
 * @return array
 *   An array of menu items.
 */
function contribute_menu() {
  $items = array(
    'questions/ask' => array(
      'title' => 'Ask a Question',
      'access callback' => 'user_is_logged_in',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('contribute_question_form'),
    ),
    'scores/%' => array(
      'title' => 'scores to a user',
      'access arguments' => array('access content'),
      'access callback' => TRUE,
      'page callback' => '_gimme_scores',
      'page arguments' => array(1),
      'type' => MENU_CALLBACK,
    ),
  );

  return $items;
}
